[package]
name = "budget-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ]}
clap = { version = "4.5.53", features = ["derive", "unicode"] }
chrono = "0.4.42"
thiserror = "2.0.17"

[profile.release]
overflow-checks = true
